version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.10
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.10
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Cr√©ation automatique des topics √† la vol√©e
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      # Configuration pour les listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    ports:
      - "9092:9092"

  spark-master:
    build: .
    image: real-time-anomaly-spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./:/opt/bitnami/spark/app

  spark-worker:
    build: .
    image: real-time-anomaly-spark:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
    ports:
      - "8081:8081"
    volumes:
      - ./:/opt/bitnami/spark/app

  sender:
    image: python:3.10-slim
    depends_on:
      - kafka
      - spark-master
    working_dir: /app
    volumes:
      - ./:/app
    command: ["bash", "-c", "echo '‚è≥ Attente de Kafka et Spark...' && sleep 45 && echo 'üì¶ Installation kafka-python...' && pip install kafka-python && echo 'üöÄ D√©marrage g√©n√©rateur de transactions...' && python src/send_transaction.py"]
    restart: "no"

